
package gorselprogramlama;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import sun.applet.Main;


public class biletsatis extends javax.swing.JFrame {

   
    public biletsatis() {
        initComponents();
        YOLCULAR();
        ASID.setEditable(false);
        BİLETLER();
        SATIS();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        YolcuID = new javax.swing.JComboBox();
        ASID = new javax.swing.JTextField();
        TRENID = new javax.swing.JComboBox();
        ÜCRETID = new javax.swing.JTextField();
        SATB = new javax.swing.JButton();
        SIFIRLAB = new javax.swing.JButton();
        GERİB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SATILTB = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("BİLET SATIŞ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("YOLCU NUMARASI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("AD SOYAD");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("TREN NUMARASI");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ÜCRET");

        YolcuID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        YolcuID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YolcuIDMouseClicked(evt);
            }
        });
        YolcuID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YolcuIDActionPerformed(evt);
            }
        });

        ASID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ASID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASIDActionPerformed(evt);
            }
        });

        TRENID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        ÜCRETID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        SATB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SATB.setText("SAT");
        SATB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SATBMouseClicked(evt);
            }
        });
        SATB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SATBActionPerformed(evt);
            }
        });

        SIFIRLAB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SIFIRLAB.setText("SIFIRLA");
        SIFIRLAB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIFIRLABMouseClicked(evt);
            }
        });
        SIFIRLAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIFIRLABActionPerformed(evt);
            }
        });

        GERİB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GERİB.setText("GERİ");
        GERİB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GERİBMouseClicked(evt);
            }
        });

        SATILTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "AD SOYAD", "TREN NUMARASI", "ÜCRET"
            }
        ));
        jScrollPane1.setViewportView(SATILTB);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("SATILAN BİLETLER");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Omer\\Documents\\NetBeansProjects\\gorselprogramlama\\icon\\plane-tickets (2).png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(381, 381, 381))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(561, 561, 561)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TRENID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ÜCRETID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SATB, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(SIFIRLAB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(YolcuID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(ASID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(131, 131, 131)))))
                .addGap(58, 58, 58)
                .addComponent(GERİB, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YolcuID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ASID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TRENID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ÜCRETID, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GERİB, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(SIFIRLAB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SATB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SIFIRLABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIFIRLABActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SIFIRLABActionPerformed

    private void SATBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SATBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SATBActionPerformed
Connection con = null;
PreparedStatement pst = null;
ResultSet Rs =null,Rsl = null;
Statement St = null,Stl = null;
private void YOLCULAR()
{
try {
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rezervasyondb","root","");
    St = con.createStatement();
    String Query = "select * from yolculartbl";
    Rs = St.executeQuery(Query);
    while(Rs.next())
    {
        String YolcuNumarası = String.valueOf(Rs.getInt("YolcuNumarası"));
        YolcuID.addItem(YolcuNumarası);
    }
}catch (Exception e){

}
}
private void BİLETLER()
{
try {
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rezervasyondb","root","");
    St = con.createStatement();
    String Query = "select * from trenlertbl";
    Rs = St.executeQuery(Query);
    while(Rs.next())
    {
        String TrenNumarası = Rs.getString("TrenNumarası");
        TRENID.addItem(TrenNumarası);
    }
}catch (Exception e){

}
}
private void BİLETLERData()
{
    String Query = "select * from  yolculartbl where YolcuNumarası="+YolcuID.getSelectedItem().toString();
    Statement St;
    ResultSet Rs;
    try{
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rezervasyondb","root","");
        St = con.createStatement();
        Rs =St.executeQuery(Query);
        if(Rs.next())
                {
                   ASID.setText(Rs.getString("adsoyad"));
                   
                   
                }
    }catch (Exception e){
        
    }
}
private void SATIS()
{
    try{
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rezervasyondb","root","");
        St = con.createStatement();
        Rs = St.executeQuery("select * from  biletsatistbl");
        SATILTB.setModel(DbUtils.resultSetToTableModel(Rs));
    } catch (Exception e){
        
    }
        }
        int BiletNumarası = 1;
private void Countbiletler()
{
   try{
       Stl = con.createStatement();
       Rsl =Stl.executeQuery("select Max(BiletNumarası) from biletsatistbl");
       Rsl.next();
       BiletNumarası=Rsl.getInt(1)+1;
       
   } catch (Exception e){
   }
}
    private void SATBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SATBMouseClicked
      if(YolcuID.getSelectedIndex()== -1  || TRENID.getSelectedIndex()== -1 || ÜCRETID.getText().isEmpty())
{
    JOptionPane.showMessageDialog(this, "EKSİK BİLGİ");
}else{
    try{
        Countbiletler();
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rezervasyondb","root","");
        PreparedStatement Add = con.prepareStatement("insert into biletsatistbl values(?,?,?,?,?)");
        Add.setInt(1, BiletNumarası);
        Add.setString(2, YolcuID.getSelectedItem().toString());
        Add.setString(3, ASID.getText());
        Add.setString(4, TRENID.getSelectedItem().toString());
        Add.setInt(5,Integer.valueOf(ÜCRETID.getText()));
        int row = Add.executeUpdate();
        JOptionPane.showMessageDialog(this, "BİLET SATILDI");
        con.close();
        SATIS();
        Clear();
        
    }catch (SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(this, e);
    }
}  
    }//GEN-LAST:event_SATBMouseClicked

    private void YolcuIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YolcuIDMouseClicked
      BİLETLERData();
    }//GEN-LAST:event_YolcuIDMouseClicked

    private void YolcuIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YolcuIDActionPerformed
      BİLETLERData();
    }//GEN-LAST:event_YolcuIDActionPerformed

    private void ASIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ASIDActionPerformed

    private void GERİBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GERİBMouseClicked
        new anasayfa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GERİBMouseClicked
private void Clear()
{
  TRENID.setSelectedIndex(-1);
        ASID.setText("");
        
        ÜCRETID.setText("");  
}
    private void SIFIRLABMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIFIRLABMouseClicked
       Clear();
        
    }//GEN-LAST:event_SIFIRLABMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(biletsatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(biletsatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(biletsatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(biletsatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new biletsatis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ASID;
    private javax.swing.JButton GERİB;
    private javax.swing.JButton SATB;
    private javax.swing.JTable SATILTB;
    private javax.swing.JButton SIFIRLAB;
    private javax.swing.JComboBox TRENID;
    private javax.swing.JComboBox YolcuID;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ÜCRETID;
    // End of variables declaration//GEN-END:variables

    private void SATILTB() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
