/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gorselprogramlama;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Omer
 */
public class biletiptal extends javax.swing.JFrame {

    /**
     * Creates new form biletiptal
     */
    public biletiptal() {
        initComponents();
        BİLETLER();
        TrenID.setEditable(false);
        İPTAL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BiletID = new javax.swing.JComboBox();
        TrenID = new javax.swing.JTextField();
        İPTALET = new javax.swing.JButton();
        SIFIRLA = new javax.swing.JButton();
        GERİ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        İPTALTABLO = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        İPTALTARİHİ = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("BİLET İPTAL");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("BİLET NUMARASI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("TREN NUMARASI");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("İPTAL TARİHİ");

        BiletID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BiletID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiletIDActionPerformed(evt);
            }
        });

        TrenID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TrenID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrenIDActionPerformed(evt);
            }
        });

        İPTALET.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        İPTALET.setText("İPTAL ET");
        İPTALET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                İPTALETMouseClicked(evt);
            }
        });
        İPTALET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                İPTALETActionPerformed(evt);
            }
        });

        SIFIRLA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SIFIRLA.setText("SIFIRLA");
        SIFIRLA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIFIRLAMouseClicked(evt);
            }
        });
        SIFIRLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIFIRLAActionPerformed(evt);
            }
        });

        GERİ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GERİ.setText("GERİ");
        GERİ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GERİMouseClicked(evt);
            }
        });
        GERİ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GERİActionPerformed(evt);
            }
        });

        İPTALTABLO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "BİLET NUMARASI", "TREN NUMARASI", "İPTAL TARİHİ"
            }
        ));
        jScrollPane1.setViewportView(İPTALTABLO);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("İPTAL EDİLEN BİLETLR");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Omer\\Documents\\NetBeansProjects\\gorselprogramlama\\icon\\cancelled (2).png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(İPTALET, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SIFIRLA, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GERİ, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BiletID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TrenID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(İPTALTARİHİ, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)))
                .addGap(213, 213, 213))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(İPTALTARİHİ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BiletID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TrenID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(İPTALET, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SIFIRLA, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GERİ, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void İPTALETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_İPTALETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_İPTALETActionPerformed

    private void SIFIRLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIFIRLAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SIFIRLAActionPerformed

    private void TrenIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrenIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrenIDActionPerformed

    private void BiletIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiletIDActionPerformed
       TRENNUMARASI();
    }//GEN-LAST:event_BiletIDActionPerformed
private void sil()
{
    try {
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rezervasyondb","root","");
             String Query ="DELETE from biletsatistbl where  BiletNumarası="+BiletID.getSelectedItem();
             Statement Del =con.createStatement();
             Del.executeUpdate(Query);
             JOptionPane.showMessageDialog(this, "BİLET SİLİNDİ");
             //TKTABLO();
                     
        }catch (SQLException | HeadlessException e){
             JOptionPane.showMessageDialog(this,e);
        }
}
    private void GERİActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GERİActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GERİActionPerformed

    private void GERİMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GERİMouseClicked
        new anasayfa().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_GERİMouseClicked
Connection con = null;
PreparedStatement pst = null;
ResultSet Rs =null,Rsl = null;
Statement St = null,Stl = null;
    private void BİLETLER()
{
try {
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rezervasyondb","root","");
    St = con.createStatement();
    String Query = "select * from biletsatistbl";
    Rs = St.executeQuery(Query);
    while(Rs.next())
    {
        int B = Rs.getInt("BiletNumarası");
        BiletID.addItem(B);
    }
}catch (Exception e){

}
}

private void TRENNUMARASI()
{
    String Query = "select * from  biletsatistbl where BiletNumarası="+BiletID.getSelectedItem().toString();
    Statement St;
    ResultSet Rs;
    try{
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rezervasyondb","root","");
        St = con.createStatement();
        Rs =St.executeQuery(Query);
        if(Rs.next())
                {
                   TrenID.setText(Rs.getString("TrenNumarası"));
                   
                   }
    }catch (Exception e){
        
    }
}
private void İPTAL()
{
    try{
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rezervasyondb","root","");
        St = con.createStatement();
        Rs = St.executeQuery("select * from  iptaltbl");
        İPTALTABLO.setModel(DbUtils.resultSetToTableModel(Rs));
    } catch (Exception e){
        
    }
        }
        int İPTALNUMARASI = 1;
private void Countiptal()
{
   try{
       Stl = con.createStatement();
       Rsl =Stl.executeQuery("select Max(BiletİptalNumarası) from iptaltbl");
       Rsl.next();
       İPTALNUMARASI=Rsl.getInt(1)+1;
       
   } catch (Exception e){
   }
}
    private void SIFIRLAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIFIRLAMouseClicked
        
    }//GEN-LAST:event_SIFIRLAMouseClicked

    private void İPTALETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_İPTALETMouseClicked
        if(TrenID.getText().isEmpty())
{
    JOptionPane.showMessageDialog(this, "EKSİK BİLGİ");
}else{
    try{
        Countiptal();
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rezervasyondb","root","");
        PreparedStatement Add = con.prepareStatement("insert into iptaltbl values(?,?,?,?)");
        
        Add.setInt(1, İPTALNUMARASI);
        Add.setInt(2,Integer.valueOf(BiletID.getSelectedItem().toString()) );
        Add.setString(3, TrenID.getText());
        Add.setString(4, İPTALTARİHİ.getDate().toString());
        int row = Add.executeUpdate();
        JOptionPane.showMessageDialog(this, "BİLET İPTAL EDİLDİ");
        con.close();
        sil();
        BİLETLER();
    }catch (SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(this, e);
    }
}
    }//GEN-LAST:event_İPTALETMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(biletiptal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(biletiptal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(biletiptal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(biletiptal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new biletiptal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BiletID;
    private javax.swing.JButton GERİ;
    private javax.swing.JButton SIFIRLA;
    private javax.swing.JTextField TrenID;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton İPTALET;
    private javax.swing.JTable İPTALTABLO;
    private com.toedter.calendar.JDateChooser İPTALTARİHİ;
    // End of variables declaration//GEN-END:variables
}
